# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'MoodMusic'

target 'MoodMusic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoodMusic
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'SpotifyLogin', '~> 0.1'
end
